<?php

namespace AppBundle\Repository\Harvest;


/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends \Doctrine\ORM\EntityRepository
{
	public function clearSeenOnLastSync() {

		$entityName = $this->getEntityName();
		$qb = $this->getEntityManager()->createQueryBuilder();

		$query = $qb->update($entityName, 'en')
		            ->set('en.seenOnLastSync', ':seenOnLastSync')
		            ->setParameter(':seenOnLastSync', false)
		            ->getQuery();

		$query->execute();
	}

	public function deleteAllNotSeenOnLastSync() {
		$entityName = $this->getEntityName();
		$qb = $this->getEntityManager()->createQueryBuilder();

		$query = $qb->delete($entityName, 'en')
					->where('en.seenOnLastSync = :seenOnLastSync')
					->setParameter(':seenOnLastSync', false)
					->getQuery();

		$query->execute();
	}
}
