<?php

namespace AppBundle\Repository\Harvest;

/**
 * ProjectAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectAssignmentRepository extends BaseRepository
{
}
