<?php

namespace AppBundle\Repository\Harvest;

/**
 * TaskAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
