<?php

namespace AppBundle\Repository\Harvest;

/**
 * TimeEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
