<?php

namespace AppBundle\Repository\Harvest;

/**
 * UserAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAssignmentRepository extends BaseRepository
{
}
